src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @ORM\Table(name="events")
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $location;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2, nullable=true)
     * @Assert\PositiveOrZero
     */
    private $price;

    /**
     * @Assert\NotBlank
     * @Assert\Length(min=15, minMessage="La description de l'évènement doit être au moins de {{ limit }} caractères !")
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @Assert\NotBlank
     * @Assert\GreaterThanOrEqual("+1 hour Europe/Paris")
     * @ORM\Column(type="datetime_immutable")
     */
    private $startsAt;

    /**
     * @ORM\Column(type="string", length=255, options={"default":"placeholder.jpg"})
     * @Assert\Regex("/^\w+\.(jpe?g|png)$/i")
     */
    private $imageFileName;

    /**
     * @ORM\Column(type="integer", options={"default":1})
     * @Assert\Positive
     */
    private $capacity;

    /**
     * @ORM\OneToMany(targetEntity=Registration::class, mappedBy="event", orphanRemoval=true)
     */
    private $registrations;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartsAt(): ?\DateTimeImmutable
    {
        return $this->startsAt;
    }

    public function setStartsAt(\DateTimeImmutable $startsAt): self
    {
        $this->startsAt = $startsAt;

        return $this;
    }


    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->imageFileName;
    }

    public function setImageFileName(?string $imageFileName): self
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setEvent($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getEvent() === $this) {
                $registration->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * Vérifiez si l'événement est gratuit ou non.
     */
    public function isFree(): bool
    {
        return $this->getPrice() == 0 or is_null($this->getPrice());
    }

    /**
     * Le nombre de places restantes pour cet événement.
     */
    public function getSpotsLeft(): int
    {
        return $this->getCapacity() - $this->getRegistrations()->count();
    }

    /**
     * Vérifiez s'il n'y a plus de places disponibles pour cet événement.
     */
    public function isSoldOut(): bool
    {
        return $this->getSpotsLeft() === 0;
    }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;


use App\Entity\Event;
use App\Form\EventFormType;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EventsController extends AbstractController
{
    #[Route('/', methods: 'GET', name: "app_home")]
    #[Route('/events', methods: 'GET', name: 'app_events_index')]
    public function index(EventRepository $eventRepository): Response
    {
        // $events = $eventRepository->findBy([],['startsAt' => 'ASC', 'price' => 'ASC']);

        $events = $eventRepository->findUpComming();

        return $this->render('events/index.html.twig', compact('events'));
    }

    #[Route('/events/create', methods: ['GET', 'POST'], name: 'app_events_create')]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $event = new Event;

        $form = $this->createForm(EventFormType::class, $event);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($event);
            $em->flush();

            $this->addFlash('success', 'Evenement créé avec succès');

            return $this->redirectToRoute('app_events_show', ['id' => $event->getId()]);
        }

        return $this->renderForm('events/create.html.twig', compact('form'));
    }

    #[Route('/events/{id<[0-9]+>}', methods: 'GET', name: 'app_events_show')]
    public function show(Event $event): Response
    {
        return $this->render('events/show.html.twig', compact('event'));
    }

    #[Route('/events/{id<[0-9]+>}/edit', methods: ['GET', 'POST'], name: 'app_events_edit')]
    public function edit(Event $event, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(EventFormType::class, $event);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', 'Evénement mis à jour.');

            return $this->redirectToRoute('app_events_show', ['id' => $event->getId()]);
        }

        return $this->renderForm('events/edit.html.twig', [
            'event' => $event,
            'form' => $form
        ]);
    }

    #[Route('/events/{id<[0-9]+>}/delete', methods: 'POST', name: 'app_events_delete')]
    public function delete(Request $request, Event $event, EntityManagerInterface $em): Response
    {
        if ($this->isCsrfTokenValid('event_deletion_' . $event->getId(), $request->request->get('csrf_token'))) {
            $em->remove($event);
            $em->flush();

            $this->addFlash(
                'danger',
                sprintf('Evenement %s éffacé !', $event->getName())
            );
        }

        return $this->redirectToRoute('app_events_index');
    }
}

templates/events/_form.html.twig
      {{ form_start(form) }}
      {{ form_widget(form) }}

      <div class="d-flex justify-content-around">
         <button type="submit" class="m-3 btn btn-sm btn-outline-success" formvalidate>
            {{ submitButtonText ?? 'Créer Evénement' }}
         </button>

         <a class="m-3 btn btn-sm btn-outline-danger" href="{{ path('app_events_index') }}"> 
            Annuler 
         </a>

      </div>

      {{ form_end(form) }}

templates/events/create.html.twig
{% extends "layouts/base.html.twig" %}

{% block title 'Créer un nouvel évenement' %}

{% block body %}
<div class="mt-5 row">
   <div class="col-md-6 mx-auto">
      <h1>Créer un nouvel évenement</h1>

      {{ include('events/_form.html.twig') }}
      
   </div>
</div>
{% endblock %}

templates/events/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Modifier ' ~ event.name %}

{% block body %}
<div class="mt-5 row">
   <div class="col-md-6 mx-auto">
      <h1>Modifier {{ event.name }} </h1>

      {{ include('events/_form.html.twig', { submitButtonText: 'Mettre à jour' }) }}

   </div>
</div>
{% endblock %}

templates/events/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Discover All Events | ' ~ parent() %}

{% block body %}
<h1 class="my-5 h3 text-center">{{ pluralize(events|length, 'Event') }}</h1>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for event in events %}
    <div class="col">
        <div class="card h-100">
            <a href="{{ path('app_events_show', {'id': event.id}) }}">
                <img
                    src="{{ asset('build/images/' ~ event.imageFileName) }}"
                    class="card-img-top img-fluid" 
                    alt="{{ event.name }}"
                    height="250"
                >
            </a>
            <div class="card-body">
                <h2 class="h5 card-title">
                    <a href="{{ path('app_events_show', {'id': event.id}) }}">{{ event.name }}</a>
                </h2>
                <h4 class="h6 text-muted">
                    {% if event.isSoldOut %}
                        <span class="badge bg-danger text-uppercase"> Complet </span>
                    {% else %}
                        {{ pluralize(event.spotsLeft, 'place') }}
                    {% endif %}
                    &bull; {{ format_price(event) }}
                </h4>
                <p class="mt-4 card-text">
                    {{ event.description|u.truncate(140, '...', false) }}
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        On {{ event.startsAt|datetime }} in {{ event.location }}
                    </small>
                </p>
                <div class="d-flex justify-content-space-between" id="action">
                    <a class="btn-sm btn btn-warning" href="{{ path('app_events_edit', {'id': event.id}) }}"> Modifier
                    </a>

                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/events/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title event.name %}

{% block body %}
	<div class="mt-5 row">
		<div class="col-md-6 mx-auto">
			<div class="card">
				<img src="{{ asset('build/images/' ~ event.imageFileName) }}" class="card-img-top img-fluid" alt="{{ event.name }}" height="250">

				<div class="card-body">
					<h1 class="h4 card-title">{{ event.name }}</h1>
					<h3 class="h5 text-muted">
						{% if not event.isSoldOut %}
                            {{ pluralize(event.spotsLeft, 'place') }} &bull; 
                        {% endif %} {{ format_price(event) }}
					</h3>
					<p>
						<a 
							class="p-1 bg-info link-dark text-decoration-none rounded fw-bold h6" 
							href="{{ path('app_event_registrations_index', {'event': event.id}) }}">
							👥 Qui est inscrit ?
						</a>
					</p>
					<p class="mt-4 card-text">
						{{ event.description | raw}}
					</p>

					<p class="card-text">
						<small class="text-muted">
							Le
							{{ event.startsAt | datetime }}
							<br>
							{{ event.location }}
						</small>
					</p>

					<div class="mb-3 d-grid">
                        {{ register_link_or_sold_out(event) }}
                    </div>

					<div class="d-flex justify-content-around">
						<a class="btn btn-outline-warning me-1" href="{{ path('app_events_edit', {'id': event.id}) }}">Modifier !!</a>
						<a class="btn btn-outline-danger ms-1" href="#" onclick="event.preventDefault(); confirm('Êtes-vous sûr?') && document.getElementById('js-event-deletion-form').submit();">Effacer</a>
						<form id="js-event-deletion-form" style="display: none;" action="{{ path('app_events_delete', {'id': event.id}) }}" method="POST">
							<input type="hidden" name="csrf_token" value="{{ csrf_token('event_deletion_' ~ event.id) }}">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}